"use client";

import { FormEvent, useEffect, useState } from "react";
import { collection, limit, onSnapshot, orderBy, query, Timestamp } from "firebase/firestore";
import { LoaderCircle, Megaphone, Send } from "lucide-react";
import { auth, db } from "@/lib/firebase";
import type { CampaignAudience, NotificationCampaign } from "@/types/notifications";

const initial = { title: "", message: "", type: "promotion", audience: "all_users" as CampaignAudience, selectedUser: "", actionUrl: "", couponCode: "", discountPercentage: "", scheduledAt: "", expiresAt: "", sendNow: true, active: true };
function displayDate(value: unknown) { return value instanceof Timestamp ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(value.toDate()) : "—"; }

export default function AdminNotificationsPage() {
  const [form, setForm] = useState(initial); const [campaigns, setCampaigns] = useState<NotificationCampaign[]>([]);
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [confirming, setConfirming] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => onSnapshot(query(collection(db, "notificationCampaigns"), orderBy("createdAt", "desc"), limit(30)), snapshot => { setCampaigns(snapshot.docs.map(document => ({ campaignId: document.id, ...document.data() } as NotificationCampaign))); setLoading(false); }, () => { setError("Unable to load notification campaigns."); setLoading(false); }), []);
  function field<K extends keyof typeof initial>(key: K, value: (typeof initial)[K]) { setForm(previous => ({ ...previous, [key]: value })); setError(""); setSuccess(""); }
  function validate() { if (form.title.trim().length < 3) return "Enter a campaign title."; if (form.message.trim().length < 3) return "Enter a campaign message."; if (form.actionUrl && !/^\/(?!\/)[^\s]*$/.test(form.actionUrl)) return "Action URL must be a local route beginning with /."; const discount = form.discountPercentage === "" ? null : Number(form.discountPercentage); if (discount !== null && (!Number.isFinite(discount) || discount < 0 || discount > 100)) return "Discount percentage must be between 0 and 100."; if (form.audience === "selected_user" && !form.selectedUser.trim()) return "Enter the selected user email or UID."; if (form.scheduledAt && form.expiresAt && new Date(form.expiresAt) <= new Date(form.scheduledAt)) return "Expiry must be after the scheduled time."; if (form.expiresAt && new Date(form.expiresAt) <= new Date()) return "Expiry must be in the future."; return ""; }
  function requestConfirmation(event: FormEvent) { event.preventDefault(); const message = validate(); if (message) { setError(message); return; } setConfirming(true); }
  async function submit() {
    const user = auth.currentUser; if (!user) { setError("Please login again."); return; }
    try { setSubmitting(true); setError(""); const token = await user.getIdToken(); const response = await fetch("/api/admin/notifications", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...form, requestId: crypto.randomUUID(), discountPercentage: form.discountPercentage === "" ? null : Number(form.discountPercentage), scheduledAt: form.scheduledAt ? new Date(form.scheduledAt).toISOString() : null, expiresAt: form.expiresAt ? new Date(form.expiresAt).toISOString() : null }) }); const result = await response.json() as { campaignId?: string; message?: string; status?: string }; if (!response.ok) throw new Error(result.message ?? "Unable to create campaign.");
      let sentMessage = result.status === "scheduled" ? "Campaign saved as scheduled. A trusted scheduler is required for automatic delivery." : "Campaign saved.";
      if (form.sendNow && result.status !== "scheduled" && result.campaignId) { const sendResponse = await fetch(`/api/admin/notifications/${result.campaignId}/send`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); const sendResult = await sendResponse.json() as { sentCount?: number; message?: string }; if (!sendResponse.ok) throw new Error(sendResult.message ?? "Campaign saved but could not be sent."); sentMessage = `Campaign sent to ${sendResult.sentCount ?? 0} recipients.`; }
      setSuccess(sentMessage); setForm(initial); setConfirming(false);
    } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : "Unable to create campaign."); setConfirming(false); } finally { setSubmitting(false); }
  }
  async function sendCampaign(campaignId: string) { const user = auth.currentUser; if (!user) return; try { setError(""); const response = await fetch(`/api/admin/notifications/${campaignId}/send`, { method: "POST", headers: { Authorization: `Bearer ${await user.getIdToken()}` } }); const result = await response.json() as { sentCount?: number; message?: string }; if (!response.ok) throw new Error(result.message); setSuccess(`Campaign sent to ${result.sentCount ?? 0} recipients.`); } catch (sendError) { setError(sendError instanceof Error ? sendError.message : "Unable to send campaign."); } }

  return <div className="space-y-8"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">Communications</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Notifications</h1><p className="mt-2 text-sm text-white/45">Create secure in-app announcements and promotions.</p></div>
    <form onSubmit={requestConfirmation} className="rounded-3xl border border-white/10 bg-white/[0.035] p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><Field label="Title" value={form.title} onChange={value => field("title", value)} /><Field label="Message" value={form.message} onChange={value => field("message", value)} multiline /><Select label="Notification type" value={form.type} onChange={value => field("type", value)} options={["promotion", "announcement", "service_alert", "system"]} /><Select label="Target audience" value={form.audience} onChange={value => field("audience", value as CampaignAudience)} options={["all_users", "customers", "drivers", "fleet_owners", "selected_user"]} />{form.audience === "selected_user" && <Field label="Selected user email or UID" value={form.selectedUser} onChange={value => field("selectedUser", value)} />}<Field label="Action URL (optional)" value={form.actionUrl} onChange={value => field("actionUrl", value)} placeholder="/book" /><Field label="Coupon code (advertising only)" value={form.couponCode} onChange={value => field("couponCode", value.toUpperCase())} /><Field label="Discount percentage (advertising only)" type="number" value={form.discountPercentage} onChange={value => field("discountPercentage", value)} /><Field label="Valid from / scheduled time" type="datetime-local" value={form.scheduledAt} onChange={value => field("scheduledAt", value)} /><Field label="Expiry" type="datetime-local" value={form.expiresAt} onChange={value => field("expiresAt", value)} /></div><div className="mt-5 flex flex-wrap gap-5"><Check label="Send now" checked={form.sendNow} onChange={value => field("sendNow", value)} /><Check label="Active" checked={form.active} onChange={value => field("active", value)} /></div><p className="mt-3 text-xs text-white/35">Coupon details are informational only and do not alter booking fares.</p>{error && <p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}{success && <p role="status" className="mt-4 text-sm text-emerald-300">{success}</p>}<button type="submit" disabled={submitting} className="mt-6 flex items-center gap-2 rounded-xl bg-amber-400 px-6 py-3 font-bold text-black disabled:opacity-50"><Megaphone size={18} /> Review campaign</button></form>
    {confirming && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4" role="dialog" aria-modal="true" aria-label="Confirm notification campaign"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#0b1018] p-6"><h2 className="text-xl font-bold">Confirm campaign</h2><p className="mt-3 text-sm text-white/55">{form.sendNow ? "This notification will be sent to the selected audience now." : "This campaign will be saved without immediate delivery."}</p><p className="mt-3 font-semibold text-amber-400">{form.title}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setConfirming(false)} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Cancel</button><button type="button" onClick={() => void submit()} disabled={submitting} className="flex items-center gap-2 rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-black">{submitting ? <LoaderCircle size={17} className="animate-spin" /> : <Send size={17} />} Confirm</button></div></div></div>}
    <section><h2 className="text-xl font-bold">Campaign history</h2>{loading ? <LoaderCircle className="mt-6 animate-spin text-amber-400" /> : campaigns.length === 0 ? <div className="mt-5 rounded-3xl border border-dashed border-white/10 p-12 text-center text-white/40">No campaigns created yet.</div> : <div className="mt-5 grid gap-4">{campaigns.map(campaign => <article key={campaign.campaignId} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{campaign.title}</h3><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] uppercase text-white/45">{campaign.status}</span></div><p className="mt-2 text-sm text-white/50">{campaign.message}</p><p className="mt-3 text-xs text-white/35">Audience: {campaign.audience.replaceAll("_", " ")} · Sent: {campaign.sentCount ?? 0} · Created: {displayDate(campaign.createdAt)} · Expiry: {displayDate(campaign.expiresAt)}</p></div>{["draft", "active"].includes(campaign.status) && <button type="button" onClick={() => void sendCampaign(campaign.campaignId)} className="flex shrink-0 items-center gap-2 rounded-xl border border-amber-400/25 px-4 py-2 text-sm font-bold text-amber-400"><Send size={16} /> Send</button>}</div></article>)}</div>}</section>
  </div>;
}

function Field({ label, value, onChange, type = "text", multiline = false, placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; multiline?: boolean; placeholder?: string }) { const classes = "mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none focus:border-amber-400/50"; return <label className={multiline ? "sm:col-span-2 text-sm text-white/60" : "text-sm text-white/60"}>{label}{multiline ? <textarea value={value} onChange={event => onChange(event.target.value)} rows={4} className={classes} /> : <input type={type} value={value} placeholder={placeholder} onChange={event => onChange(event.target.value)} className={classes} />}</label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-sm text-white/60">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1018] px-4 py-3 text-white outline-none focus:border-amber-400/50">{options.map(option => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>; }
function Check({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-3 text-sm text-white/60"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="accent-amber-400" />{label}</label>; }
