"use client";

import { useEffect, useState } from "react";
import { collection, doc, onSnapshot, serverTimestamp, setDoc } from "firebase/firestore";
import { Car, LoaderCircle, Save } from "lucide-react";
import { auth, db } from "@/lib/firebase";

const fields = ["baseFare", "perKm", "perMinute", "minimumKm", "minimumFare", "waitingCharge", "nightCharge", "platformCharge", "driverAllowance", "gst", "seats"] as const;
type Pricing = Record<(typeof fields)[number], number> & { name: string; description: string; enabled: boolean };
const empty: Pricing = { name: "", description: "", baseFare: 0, perKm: 0, perMinute: 0, minimumKm: 1, minimumFare: 0, waitingCharge: 0, nightCharge: 0, platformCharge: 0, driverAllowance: 0, gst: 0, seats: 4, enabled: true };

export default function PricingPage() {
  const [vehicles, setVehicles] = useState<Array<{ id: string; data: Pricing }>>([]); const [selectedId, setSelectedId] = useState(""); const [pricing, setPricing] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => onSnapshot(collection(db, "settings"), snapshot => { const next = snapshot.docs.map(item => ({ id: item.id, data: { ...empty, ...item.data() } as Pricing })); setVehicles(next); if (!selectedId && next[0]) { setSelectedId(next[0].id); setPricing(next[0].data); } setLoading(false); }, () => { setError("Unable to load pricing settings."); setLoading(false); }), [selectedId]);
  function select(id: string) { setSelectedId(id); setPricing(vehicles.find(item => item.id === id)?.data ?? empty); setMessage(""); setError(""); }
  async function save() { const id = selectedId.trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-"); if (!id) { setError("Enter a vehicle pricing ID."); return; } if (!pricing.name.trim()) { setError("Enter the vehicle name."); return; } if (fields.some(field => !Number.isFinite(pricing[field]) || pricing[field] < 0)) { setError("Pricing values cannot be negative or invalid."); return; } if (pricing.minimumKm < 1 || pricing.seats < 1) { setError("Minimum kilometres and seats must be at least 1."); return; } try { setSaving(true); setError(""); await setDoc(doc(db, "settings", id), { ...pricing, name: pricing.name.trim(), description: pricing.description.trim(), updatedAt: serverTimestamp(), updatedBy: auth.currentUser?.uid ?? "" }, { merge: true }); setSelectedId(id); setMessage("Vehicle pricing saved."); } catch { setError("Unable to save vehicle pricing."); } finally { setSaving(false); } }
  if (loading) return <LoaderCircle className="animate-spin text-amber-400" />;
  return <div className="space-y-7"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">Fare Configuration</p><h1 className="mt-2 text-3xl font-bold">Pricing Management</h1><p className="mt-2 text-sm text-white/45">Manage vehicle pricing used by the booking fare calculator.</p></div><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="space-y-2 rounded-2xl border border-white/10 bg-white/[0.03] p-3"><button onClick={() => { setSelectedId("new-vehicle"); setPricing(empty); }} className="w-full rounded-xl bg-amber-400 px-4 py-3 font-bold text-black">Add pricing</button>{vehicles.map(vehicle => <button key={vehicle.id} onClick={() => select(vehicle.id)} className={`w-full rounded-xl px-4 py-3 text-left ${selectedId === vehicle.id ? "bg-white/10 text-amber-300" : "text-white/55"}`}>{vehicle.data.name || vehicle.id}</button>)}</aside><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Pricing ID" value={selectedId} onChange={setSelectedId} /><Field label="Vehicle name" value={pricing.name} onChange={value => setPricing(previous => ({ ...previous, name: value }))} /><Field label="Description" value={pricing.description} onChange={value => setPricing(previous => ({ ...previous, description: value }))} />{fields.map(field => <Field key={field} label={field.replace(/([A-Z])/g, " $1")} type="number" value={String(pricing[field])} onChange={value => setPricing(previous => ({ ...previous, [field]: Number(value) }))} />)}<label className="flex items-center gap-3 text-sm text-white/60"><input type="checkbox" checked={pricing.enabled} onChange={event => setPricing(previous => ({ ...previous, enabled: event.target.checked }))} className="accent-amber-400" />Available for booking</label></div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}{message && <p className="mt-4 text-sm text-emerald-300">{message}</p>}<button onClick={() => void save()} disabled={saving} className="mt-6 flex items-center gap-2 rounded-xl bg-amber-400 px-6 py-3 font-bold text-black disabled:opacity-50">{saving ? <LoaderCircle className="animate-spin" size={18} /> : <Save size={18} />}Save pricing</button></section></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-sm text-white/45"><Car className="mb-2 text-amber-400" />Changes apply to new fare estimates. Existing bookings retain their saved breakdown.</div></div>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label><span className="mb-2 block text-sm capitalize text-white/50">{label}</span><input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={event => onChange(event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 outline-none focus:border-amber-400/50" /></label>; }
