"use client";

import { useEffect, useMemo, useState } from "react";
import { collection, onSnapshot, type DocumentData } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { LoaderCircle, Search } from "lucide-react";

export default function ApplicationReviewList({ kind }: { kind: "driver" | "vehicle" }) {
  const collectionName = kind === "driver" ? "driverApplications" : "vehicleOwnerApplications";
  const [items, setItems] = useState<Array<DocumentData & { id: string }>>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [selected, setSelected] = useState<(DocumentData & { id: string }) | null>(null); const [notes, setNotes] = useState(""); const [action, setAction] = useState(""); const [error, setError] = useState("");
  useEffect(() => onSnapshot(collection(db, collectionName), snapshot => { setItems(snapshot.docs.map(item => ({ id: item.id, ...item.data() }))); setLoading(false); }, () => { setError("Unable to load applications."); setLoading(false); }), [collectionName]);
  const filtered = useMemo(() => items.filter(item => { const haystack = Object.values(item).filter(value => typeof value === "string").join(" ").toLowerCase(); return (status === "all" || item.status === status) && haystack.includes(search.toLowerCase()); }), [items, search, status]);
  async function review(nextStatus: string) { if (!selected || !auth.currentUser) return; if (["rejected", "needs_changes"].includes(nextStatus) && notes.trim().length < 3) { setError("Review notes are required for this action."); return; } try { setAction(nextStatus); setError(""); const token = await auth.currentUser.getIdToken(); const endpoint = kind === "driver" ? `/api/admin/driver-applications/${selected.id}/review` : `/api/admin/vehicle-applications/${selected.id}/review`; const response = await fetch(endpoint, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus, notes: notes.trim() }) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message || "Review failed."); setSelected(null); setNotes(""); } catch (reviewError) { setError(reviewError instanceof Error ? reviewError.message : "Review failed."); } finally { setAction(""); } }
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-amber-400">Application Review</p><h1 className="mt-2 text-3xl font-bold">{kind === "driver" ? "Driver Applications" : "Vehicle Applications"}</h1></div><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-white/30" size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search applications" className="w-full rounded-xl border border-white/10 bg-black/20 py-3 pl-11 pr-4 outline-none focus:border-amber-400/40" /></label><select value={status} onChange={event => setStatus(event.target.value)} className="rounded-xl border border-white/10 bg-[#0b1018] px-4"><option value="all">All statuses</option>{["submitted", "under_review", "needs_changes", "approved", "rejected"].map(value => <option key={value} value={value}>{value.replace(/_/g, " ")}</option>)}</select></div>{error && <div className="rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{loading ? <LoaderCircle className="animate-spin text-amber-400" /> : <div className="grid gap-4">{filtered.map(item => <button key={item.id} onClick={() => { setSelected(item); setNotes(""); }} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-left transition hover:border-amber-400/25"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{String(item.legalName ?? item.ownerName ?? "Applicant")}</h2><p className="mt-2 text-sm text-white/45">{String(item.email ?? item.ownerEmail ?? "")} · {String(item.phoneNumber ?? item.ownerPhone ?? "")}</p><p className="mt-1 text-xs text-white/35">{kind === "driver" ? `${item.city ?? ""} · ${item.licenceNumber ?? ""}` : `${item.city ?? ""} · ${item.registrationNumber ?? ""} · ${item.vehicleMake ?? ""} ${item.vehicleModel ?? ""}`}</p></div><span className="h-fit rounded-full bg-amber-400/10 px-3 py-1 text-xs capitalize text-amber-300">{String(item.status).replace(/_/g, " ")}</span></div></button>)}</div>}
    {selected && <div className="fixed inset-0 z-[100] overflow-y-auto bg-black/80 p-4"><div className="mx-auto my-8 max-w-4xl rounded-3xl border border-white/10 bg-[#0b1018] p-6 text-white"><div className="flex justify-between"><h2 className="text-2xl font-bold">Application details</h2><button onClick={() => setSelected(null)} className="text-white/50">Close</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(selected).filter(([key, value]) => !["id", "reviewHistory"].includes(key) && typeof value !== "object").map(([key, value]) => <div key={key} className="rounded-xl border border-white/10 p-3"><p className="text-xs capitalize text-white/35">{key.replace(/([A-Z])/g, " $1")}</p><p className="mt-1 break-words text-sm">{String(value)}</p></div>)}</div><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Review notes (required for rejection or requested changes)" className="mt-6 w-full rounded-xl border border-white/10 bg-black/25 p-4 outline-none" rows={3} /><div className="mt-4 flex flex-wrap gap-2">{[["under_review", "Mark under review"], ["needs_changes", "Request changes"], ["approved", "Approve"], ["rejected", "Reject"]].map(([value, label]) => <button key={value} disabled={Boolean(action)} onClick={() => void review(value)} className={`rounded-xl px-4 py-3 text-sm font-bold disabled:opacity-50 ${value === "approved" ? "bg-emerald-500" : value === "rejected" ? "bg-red-500" : "bg-amber-400 text-black"}`}>{action === value ? "Saving..." : label}</button>)}</div></div></div>}
  </div>;
}
